import { Meal } from '../types';

export const breakfastMeals: Meal[] = [
  {
    id: 'aloo-paratha',
    name: 'Aloo Paratha',
    type: 'breakfast',
    description: 'Whole wheat flatbread stuffed with spiced mashed potatoes, served with butter, yogurt, and pickle',
    region: 'north',
    ingredients: ['whole wheat flour', 'potatoes', 'onions', 'green chilies', 'spices', 'ghee'],
    cookingTime: 30,
    spiceLevel: 'medium',
    cookingMedium: ['ghee'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 350,
    protein: 8,
    carbs: 52,
    fat: 12,
    healthTags: ['high-fiber', 'protein-rich'],
    accompaniments: ['yogurt', 'pickle', 'butter'],
    alternatives: ['gobi paratha', 'paneer paratha']
  },
  {
    id: 'idli-sambar',
    name: 'Idli Sambar',
    type: 'breakfast',
    description: 'Steamed rice and lentil cakes served with spiced lentil soup and coconut chutney',
    region: 'south',
    ingredients: ['rice', 'urad dal', 'toor dal', 'vegetables', 'spices', 'coconut'],
    cookingTime: 40,
    spiceLevel: 'medium',
    cookingMedium: ['oil'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 250,
    protein: 10,
    carbs: 45,
    fat: 5,
    healthTags: ['low-fat', 'protein-rich', 'fermented'],
    accompaniments: ['coconut chutney', 'sambar', 'podi'],
    alternatives: ['dosa', 'uttapam']
  },
  {
    id: 'poha',
    name: 'Poha',
    type: 'breakfast',
    description: 'Flattened rice cooked with onions, peanuts, and spices, garnished with fresh coriander and lemon',
    region: 'west',
    ingredients: ['flattened rice', 'peanuts', 'onions', 'green chilies', 'spices', 'oil'],
    cookingTime: 20,
    spiceLevel: 'mild',
    cookingMedium: ['oil'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 280,
    protein: 7,
    carbs: 48,
    fat: 8,
    healthTags: ['quick-cook', 'light'],
    accompaniments: ['sev', 'lemon wedges', 'yogurt'],
    alternatives: ['upma', 'kanda poha']
  },
  {
    id: 'chole-bhature',
    name: 'Chole Bhature',
    type: 'breakfast',
    description: 'Spiced chickpea curry served with deep-fried bread, pickled onions, and green chutney',
    region: 'north',
    ingredients: ['chickpeas', 'flour', 'onions', 'tomatoes', 'spices', 'oil'],
    cookingTime: 45,
    spiceLevel: 'spicy',
    cookingMedium: ['oil'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 650,
    protein: 18,
    carbs: 85,
    fat: 28,
    healthTags: ['protein-rich', 'festive'],
    accompaniments: ['pickled onions', 'green chutney', 'yogurt'],
    alternatives: ['puri bhaji', 'pav bhaji']
  },
  {
    id: 'upma',
    name: 'Upma',
    type: 'breakfast',
    description: 'Savory semolina porridge cooked with vegetables and mild spices',
    region: 'south',
    ingredients: ['semolina', 'vegetables', 'curry leaves', 'mustard seeds', 'spices', 'ghee'],
    cookingTime: 25,
    spiceLevel: 'mild',
    cookingMedium: ['ghee', 'oil'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 230,
    protein: 6,
    carbs: 42,
    fat: 6,
    healthTags: ['quick-cook', 'light', 'low-fat'],
    accompaniments: ['coconut chutney', 'sambar', 'banana'],
    alternatives: ['poha', 'semiya upma']
  }
]; 