import { Meal } from '../types';

export const dinnerMeals: Meal[] = [
  {
    id: 'roti-sabzi',
    name: 'Roti Sabzi',
    type: 'dinner',
    description: 'Whole wheat flatbread served with mixed vegetable curry',
    region: 'north',
    ingredients: ['wheat flour', 'mixed vegetables', 'spices', 'oil'],
    cookingTime: 45,
    spiceLevel: 'medium',
    cookingMedium: ['oil'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 400,
    protein: 12,
    carbs: 60,
    fat: 10,
    healthTags: ['balanced-meal', 'fiber-rich'],
    accompaniments: ['salad', 'pickle', 'papad'],
    alternatives: ['paratha sabzi', 'puri sabzi']
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer with Roti',
    type: 'dinner',
    description: 'Cottage cheese cubes in creamy spinach gravy, served with rotis',
    region: 'north',
    ingredients: ['spinach', 'paneer', 'spices', 'cream', 'wheat flour'],
    cookingTime: 40,
    spiceLevel: 'medium',
    cookingMedium: ['ghee'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 550,
    protein: 22,
    carbs: 45,
    fat: 32,
    healthTags: ['protein-rich', 'iron-rich'],
    accompaniments: ['rice', 'onion', 'pickle'],
    alternatives: ['methi paneer', 'matar paneer']
  },
  {
    id: 'dal-tadka',
    name: 'Dal Tadka with Jeera Rice',
    type: 'dinner',
    description: 'Yellow lentils tempered with spices, served with cumin rice',
    region: 'north',
    ingredients: ['yellow dal', 'rice', 'cumin', 'spices', 'ghee'],
    cookingTime: 35,
    spiceLevel: 'medium',
    cookingMedium: ['ghee'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 480,
    protein: 16,
    carbs: 70,
    fat: 14,
    healthTags: ['protein-rich', 'comfort-food'],
    accompaniments: ['papad', 'pickle', 'onion'],
    alternatives: ['dal fry', 'dal makhani']
  },
  {
    id: 'dosa',
    name: 'Masala Dosa',
    type: 'dinner',
    description: 'Crispy rice and lentil crepe filled with spiced potato mixture',
    region: 'south',
    ingredients: ['rice', 'urad dal', 'potatoes', 'spices', 'oil'],
    cookingTime: 30,
    spiceLevel: 'medium',
    cookingMedium: ['oil'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 350,
    protein: 8,
    carbs: 55,
    fat: 12,
    healthTags: ['fermented', 'light'],
    accompaniments: ['sambar', 'coconut chutney', 'tomato chutney'],
    alternatives: ['plain dosa', 'rava dosa']
  },
  {
    id: 'khichdi',
    name: 'Khichdi',
    type: 'dinner',
    description: 'One-pot rice and lentil dish cooked with mild spices',
    region: 'north',
    ingredients: ['rice', 'moong dal', 'vegetables', 'spices', 'ghee'],
    cookingTime: 30,
    spiceLevel: 'mild',
    cookingMedium: ['ghee'],
    isVegetarian: true,
    hasOnionGarlic: false,
    calories: 300,
    protein: 12,
    carbs: 50,
    fat: 8,
    healthTags: ['easy-digest', 'comfort-food'],
    accompaniments: ['papad', 'pickle', 'ghee'],
    alternatives: ['dal khichdi', 'masala khichdi']
  }
]; 