import { Meal } from '../types';

export const lunchMeals: Meal[] = [
  {
    id: 'dal-chawal',
    name: 'Dal Chawal',
    type: 'lunch',
    description: 'Yellow lentils cooked with spices, served with steamed rice and ghee',
    region: 'north',
    ingredients: ['yellow dal', 'rice', 'onions', 'tomatoes', 'spices', 'ghee'],
    cookingTime: 40,
    spiceLevel: 'medium',
    cookingMedium: ['ghee'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 450,
    protein: 15,
    carbs: 75,
    fat: 12,
    healthTags: ['protein-rich', 'comfort-food'],
    accompaniments: ['papad', 'pickle', 'onion'],
    alternatives: ['khichdi', 'rajma chawal']
  },
  {
    id: 'rajma-chawal',
    name: 'Rajma Chawal',
    type: 'lunch',
    description: 'Red kidney beans curry cooked in onion-tomato gravy, served with rice',
    region: 'north',
    ingredients: ['rajma', 'rice', 'onions', 'tomatoes', 'spices', 'ghee'],
    cookingTime: 50,
    spiceLevel: 'medium',
    cookingMedium: ['ghee', 'oil'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 520,
    protein: 18,
    carbs: 80,
    fat: 14,
    healthTags: ['protein-rich', 'fiber-rich'],
    accompaniments: ['raita', 'pickle', 'onion'],
    alternatives: ['dal chawal', 'chole chawal']
  },
  {
    id: 'thali',
    name: 'Veg Thali',
    type: 'lunch',
    description: 'Complete meal with dal, sabzi, roti, rice, raita, and accompaniments',
    region: 'north',
    ingredients: ['dal', 'vegetables', 'wheat flour', 'rice', 'yogurt', 'spices'],
    cookingTime: 60,
    spiceLevel: 'medium',
    cookingMedium: ['both'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 750,
    protein: 25,
    carbs: 100,
    fat: 20,
    healthTags: ['balanced-meal', 'protein-rich'],
    accompaniments: ['pickle', 'papad', 'salad'],
    alternatives: ['mini thali', 'special thali']
  },
  {
    id: 'sambar-rice',
    name: 'Sambar Rice',
    type: 'lunch',
    description: 'Spiced lentil stew with vegetables mixed with rice',
    region: 'south',
    ingredients: ['toor dal', 'rice', 'vegetables', 'sambar powder', 'tamarind', 'oil'],
    cookingTime: 45,
    spiceLevel: 'spicy',
    cookingMedium: ['oil'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 400,
    protein: 12,
    carbs: 70,
    fat: 8,
    healthTags: ['protein-rich', 'fiber-rich'],
    accompaniments: ['papad', 'pickle', 'appalam'],
    alternatives: ['rasam rice', 'curd rice']
  },
  {
    id: 'pulao',
    name: 'Vegetable Pulao',
    type: 'lunch',
    description: 'Fragrant rice cooked with mixed vegetables and aromatic spices',
    region: 'north',
    ingredients: ['basmati rice', 'mixed vegetables', 'spices', 'ghee'],
    cookingTime: 35,
    spiceLevel: 'mild',
    cookingMedium: ['ghee'],
    isVegetarian: true,
    hasOnionGarlic: true,
    calories: 380,
    protein: 8,
    carbs: 65,
    fat: 10,
    healthTags: ['one-pot-meal', 'light'],
    accompaniments: ['raita', 'papad', 'pickle'],
    alternatives: ['biryani', 'jeera rice']
  }
]; 